version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306"
      
  webserver:
    image: webserver
    container_name: webserver
    depends_on:
      - frontend
      - backend
    ports:
      - 8082:8082
    volumes:
      - ./photos:/usr/share/nginx/html:ro
    links:
      - frontend
      - backend

  backend:
    image: backend
    container_name: backend
    depends_on:
      - mysql
    command: sh -c "/wait && ./main"
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
      DB_CONNECTION: mysql:mysql@tcp(mysql:3306)/chat?charset=utf8&parseTime=True&loc=Local
      SERVER_PORT: :3000
      IMAGE_SAVE_PATH: /images/
    volumes:
      - ./photos:/images/
    ports:
      - "3000"
    links:
      - mysql
    tty: true

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "8000"

volumes: 
  avatars:
